# Copyright (c) 2025 ADBC Drivers Contributors. All rights reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

[workspace]
authors = ["David Li <li.davidm96@gmail.com>"]
channels = ["conda-forge"]
name = "ADBC Drivers Documentation"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
build = "sphinx-build . _build -W"
clean = "rm -rf _build"
serve = "python -m http.server -d _build"

[dependencies]
python = ">=3.13.5,<3.14"
sphinx = ">=8.2.3,<9"
myst-parser = ">=4.0.1,<5"
sphinx-copybutton = ">=0.5.2,<0.6"
sphinx-design = ">=0.6.1,<0.7"

sphinx-inline-tabs = ">=2023.4.21,<2024"
sphinx-notfound-page = ">=1.1.0,<2"
sphinxext-opengraph = ">=0.12.0,<0.13"
linkify-it-py = ">=2.0.3,<3"
matplotlib = ">=3.10.6,<4"

[pypi-dependencies]
sphinx-immaterial = ">=0.13.6, <0.14"

[environments]
lint = ["lint"]
watch = ["default", "watch"]

[feature.lint.dependencies]
pre-commit = "*"

[feature.lint.tasks]
pre-commit = "pre-commit run --all-files --color=always --show-diff-on-failure --verbose"

[feature.watch.dependencies]
sphinx-autobuild = ">=2024.10.3,<2025"

[feature.watch.tasks]
watch = "sphinx-autobuild . _build"
